# Generated by Django 6.1.1 on 2026-09-21 10:54

from django.db import migrations
from django.utils import timezone


def mark_existing_users_as_verified(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    User.objects.filter(
        is_email_verified=False,
    ).update(
        is_email_verified=True,
        email_verified_at=timezone.now(),
    )


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0002_user_email_verified_at_user_is_email_verified_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            mark_existing_users_as_verified,
            migrations.RunPython.noop,
        ),
    ]