# Generated by Django 6.1.1 on 2026-09-23 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_socialidentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp_hash', models.CharField(max_length=128)),
                ('otp_expires_at', models.DateTimeField()),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('completion_token_hash', models.CharField(blank=True, max_length=64)),
                ('completion_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['otp_expires_at'], name='accounts_pe_otp_exp_c1d0ad_idx'), models.Index(fields=['completion_token_expires_at'], name='accounts_pe_complet_887e9d_idx')],
            },
        ),
    ]
