# Generated by Django 6.1.1 on 2026-09-23 16:24

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pendingregistration'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsernameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_username', models.CharField(max_length=150)),
                ('new_username', models.CharField(max_length=150)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'username history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='username_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='unique_user_username_case_insensitive'),
        ),
        migrations.AddField(
            model_name='usernamehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usernamehistory',
            index=models.Index(fields=['old_username'], name='accounts_us_old_use_07654c_idx'),
        ),
        migrations.AddIndex(
            model_name='usernamehistory',
            index=models.Index(fields=['user', 'changed_at'], name='accounts_us_user_id_98606c_idx'),
        ),
    ]
