# Generated by Django 6.1.1 on 2026-09-28 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment_confirmed', 'Payment confirmed'), ('payment_failed', 'Payment failed'), ('order_cancelled', 'Order cancelled'), ('order_processing', 'Order processing'), ('order_shipped', 'Order shipped'), ('order_delivered', 'Order delivered'), ('refund_initiated', 'Refund initiated'), ('refund_processing', 'Refund processing'), ('refund_needs_attention', 'Refund needs attention'), ('refund_processed', 'Refund processed'), ('refund_failed', 'Refund failed')], max_length=40)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('deduplication_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notification_user_read_idx'), models.Index(fields=['user', 'created_at'], name='notification_user_time_idx')],
            },
        ),
    ]
