# Generated by Django 6.1.1 on 2026-09-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('customer_cancelled', 'Cancelled by customer'), ('payment_expired', 'Payment reservation expired'), ('staff_cancelled', 'Cancelled by staff')], max_length=30, null=True),
        ),
    ]
