# Generated by Django 6.1.1 on 2026-09-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_migrate_existing_products'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='product_price_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='product_stock_non_negative',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
    ]
