# Generated by Django 6.1.1 on 2026-09-22 09:53

import django.core.validators
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_product_price_non_negative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), products.models.validate_image_size, products.models.validate_image_content]),
        ),
    ]
