# Generated by Django 6.1.1 on 2026-09-24 19:09

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_delivery_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state', 'city'],
                'indexes': [models.Index(fields=['state', 'is_active'], name='delivery_state_active_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('state'), django.db.models.functions.text.Lower('city'), name='unique_delivery_state_city_case_insensitive'), models.CheckConstraint(condition=models.Q(('shipping_fee__gte', 0)), name='delivery_shipping_fee_non_negative'), models.CheckConstraint(condition=models.Q(('estimated_delivery_days__gte', 1)), name='delivery_days_at_least_one')],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=20)),
                ('recipient_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Nigerian phone number, for example 08012345678 or +2348012345678.', regex='^(?:\\+234|0)[789]\\d{9}$')])),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Nigeria', editable=False, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_addresses', to='addresses.deliverylocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='shipping_user_default_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='one_default_shipping_address_per_user')],
            },
        ),
    ]
