# Generated by Django 6.1.1 on 2026-10-02 01:50

import json
from pathlib import Path

from django.db import migrations

EXPECTED_MODEL = "addresses.deliverylocation"
EXPECTED_RECORD_COUNT = 95


def seed_delivery_locations(apps, schema_editor):
    DeliveryLocation = apps.get_model(
        "addresses",
        "DeliveryLocation",
    )

    fixture_path = (
        Path(__file__).resolve().parents[1] / "fixtures" / "delivery_locations.json"
    )

    with fixture_path.open(
        mode="r",
        encoding="utf-8",
    ) as fixture_file:
        records = json.load(fixture_file)

    if len(records) != EXPECTED_RECORD_COUNT:
        raise RuntimeError(
            "Expected "
            f"{EXPECTED_RECORD_COUNT} delivery locations, "
            f"but found {len(records)}."
        )

    database_alias = schema_editor.connection.alias
    delivery_locations = DeliveryLocation.objects.using(
        database_alias,
    )

    for record in records:
        if record.get("model") != EXPECTED_MODEL:
            raise RuntimeError(
                "The delivery-location fixture contains " "an unexpected model."
            )

        fields = record["fields"]

        delivery_locations.update_or_create(
            state=fields["state"].strip(),
            city=fields["city"].strip(),
            defaults={
                "shipping_fee": fields["shipping_fee"],
                "estimated_delivery_days": fields["estimated_delivery_days"],
                "is_active": fields["is_active"],
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            seed_delivery_locations,
            migrations.RunPython.noop,
        ),
    ]
