# Generated by Django 6.1.1 on 2026-09-26 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_cancellation_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('returned', 'Returned')], default='preparing', max_length=20)),
                ('carrier', models.CharField(blank=True, default='', max_length=100)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='shipment_status_time_idx'), models.Index(fields=['carrier', 'status'], name='shipment_carrier_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tracking_number', ''), _negated=True), fields=('tracking_number',), name='unique_nonempty_tracking_number'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['shipped', 'delivered']), _negated=True), models.Q(models.Q(('carrier', ''), _negated=True), models.Q(('tracking_number', ''), _negated=True)), _connector='OR'), name='shipment_tracking_required'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'shipped'), _negated=True), ('shipped_at__isnull', False), _connector='OR'), name='shipment_shipped_time_required'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'delivered'), _negated=True), models.Q(('shipped_at__isnull', False), ('delivered_at__isnull', False)), _connector='OR'), name='shipment_delivery_times_required'), models.CheckConstraint(condition=models.Q(('delivered_at__isnull', True), ('shipped_at__isnull', True), ('delivered_at__gte', models.F('shipped_at')), _connector='OR'), name='shipment_delivery_after_shipping')],
            },
        ),
    ]
