# Generated by Django 6.1.1 on 2026-09-25 16:36

import django.core.validators
import django.db.models.deletion
import payments.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_cancellation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paystack', 'Paystack')], default='paystack', max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'event_type'], name='webhook_provider_event_idx'), models.Index(fields=['processed', 'created_at'], name='webhook_processed_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paystack', 'Paystack')], default='paystack', max_length=20)),
                ('reference', models.CharField(default=payments.models.generate_payment_reference, editable=False, max_length=100, unique=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('reversed', 'Reversed'), ('refunded', 'Refunded')], default='initialized', max_length=20)),
                ('provider_status', models.CharField(blank=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_subunit', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('authorization_url', models.URLField(blank=True, max_length=500)),
                ('access_code', models.CharField(blank=True, max_length=100)),
                ('provider_transaction_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('channel', models.CharField(blank=True, max_length=30)),
                ('gateway_response', models.CharField(blank=True, max_length=255)),
                ('failure_message', models.TextField(blank=True)),
                ('initialization_response', models.JSONField(blank=True, default=dict)),
                ('verification_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='payment_order_status_idx'), models.Index(fields=['provider', 'status'], name='payment_provider_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'idempotency_key'), name='unique_payment_key_per_order'), models.UniqueConstraint(condition=models.Q(('status', 'successful')), fields=('order',), name='one_successful_payment_per_order'), models.UniqueConstraint(condition=models.Q(('status__in', ['initialized', 'pending'])), fields=('order',), name='one_active_payment_per_order'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_nonnegative'), models.CheckConstraint(condition=models.Q(('amount_subunit__gt', 0)), name='payment_subunit_positive')],
            },
        ),
    ]
