# Generated by Django 6.1.1 on 2026-09-28 12:57

import django.core.validators
import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by_email', models.EmailField(blank=True, max_length=254)),
                ('reference', models.CharField(default=payments.models.generate_refund_reference, editable=False, max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack')], default='paystack', max_length=20)),
                ('provider_refund_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='initialized', max_length=20)),
                ('provider_status', models.CharField(blank=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_subunit', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(max_length=3)),
                ('reason', models.TextField(max_length=1000)),
                ('failure_message', models.TextField(blank=True)),
                ('initialization_response', models.JSONField(blank=True, default=dict)),
                ('latest_webhook_payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='payments.payment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'status'], name='refund_provider_status_idx'), models.Index(fields=['status', 'created_at'], name='refund_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive'), models.CheckConstraint(condition=models.Q(('amount_subunit__gt', 0)), name='refund_subunit_positive')],
            },
        ),
    ]
