# Generated by Django 6.1.1 on 2026-09-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('processing', 'Processing'), ('needs_attention', 'Needs attention'), ('processed', 'Processed'), ('failed', 'Failed')], default='initialized', max_length=20),
        ),
    ]
