# Generated by Django 6.1.1 on 2026-09-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('reversed', 'Reversed'), ('refunded', 'Refunded')], default='initialized', max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('processing', 'Processing'), ('needs_attention', 'Needs attention'), ('processed', 'Processed'), ('failed', 'Failed')], default='initialized', max_length=20),
        ),
    ]
